# Generated by Django 3.0.4 on 2020-04-29 19:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20200331_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
