# Generated by Django 3.0.4 on 2020-05-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_auto_20200512_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
