# Generated by Django 3.0.4 on 2020-05-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200429_2210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactform',
        ),
    ]
